-- ============================================================================
-- 四季アーカイブ出演者データ(archive_cast)
--
-- 公式アーカイブの会員ページから取った、自分用の非公開データ。
-- RLSは有効にするが、このフェーズではポリシーを作らない
-- (= 公開キー[anon/authenticated]からは誰も読めず、ダッシュボードからのみ見える)。
-- 読み取りポリシー(ログインユーザーのみ select 可)はフェーズ2で追加する。
--
-- データ投入はユーザーが変換ツール+Supabase Table EditorのCSVインポートで行う。
-- 1行 = 1公演(1年分) × 1役 × 1人。
-- ============================================================================

create table public.archive_cast (
  id bigint generated by default as identity primary key,
  year int not null,
  work text not null,
  run_name text not null,
  theater text,
  start_date date,
  end_date date,
  role text not null,
  actor text not null,
  created_at timestamptz default now(),
  unique (year, run_name, role, actor)
);

alter table public.archive_cast enable row level security;

create index archive_cast_work_role_idx on public.archive_cast (work, role);
create index archive_cast_actor_idx on public.archive_cast (actor);
