-- ============================================================================
-- アーカイブデータの再構成: 公演(archive_runs)・キャスト(archive_cast)・
-- スタッフ(archive_staff) + 横断検索ビュー(archive_people)
--
-- 旧 archive_cast(年・作品・公演名・劇場・期間・役・出演者を1行に持つ単一テーブル)
-- を、公演を中心とした3テーブル構成に作り直す。
--
-- 本番適用時の実際の手順(記録):
-- 1. 旧 archive_cast にデータ(2025年分1,644行)が入っていたため、
--    drop table ではなく rename table で archive_cast_old_v1 に退避
--    (このSupabaseプロジェクトでは、このセッションからの DROP TABLE が
--    繰り返しタイムアウトしたため、ALTER TABLE RENAME で回避した)
-- 2. 以下のSQLで新規に3テーブル+ビューを作成
-- 3. 旧テーブル(archive_cast_old_v1)は、新データの投入・動作確認が済むまで
--    バックアップとして残している。確認後に削除する場合はダッシュボードから。
-- ============================================================================

create table public.archive_runs (
  perf_key text primary key,          -- 例 1982-03
  year int not null,
  seq int not null,                   -- ページ内の順番
  run_name text not null,             -- アーカイブの公演名そのまま
  work text not null,                 -- 作品名(冠・都市名・シリーズ名を外したもの)
  theater text,                       -- 劇場。地方公演は都市名の一覧
  start_date date,
  end_date date,
  performances int,                   -- 公演回数
  schedule_text text,                 -- 公演期間・上演月日の原文
  notes text,                         -- 備考・その他の原文
  created_at timestamptz default now()
);

create table public.archive_cast (
  id bigint generated by default as identity primary key,
  perf_key text not null references public.archive_runs(perf_key),
  team text,                          -- Ａ班・Ｂ班など
  role text not null,
  actor text not null,
  actor_alias text,                   -- 「坂下廣記＝坂下広記」の右側
  created_at timestamptz default now(),
  unique nulls not distinct (perf_key, team, role, actor)
);

create table public.archive_staff (
  id bigint generated by default as identity primary key,
  perf_key text not null references public.archive_runs(perf_key),
  section text not null,              -- 作者・訳者 / 演出・スタッフ / 主催・協賛
  group_label text,                   -- 日本スタッフ、劇団四季技術部 など
  job text not null,                  -- 演出、子役担当、稽古進行管理 など
  person text not null,
  note text,                          -- レジデント・ディレクター、Ａ班 など
  created_at timestamptz default now(),
  unique nulls not distinct (perf_key, section, group_label, job, person)
);

alter table public.archive_runs  enable row level security;
alter table public.archive_cast  enable row level security;
alter table public.archive_staff enable row level security;

create index on public.archive_runs (work);
create index on public.archive_cast (actor);
create index on public.archive_cast (perf_key, role);
create index on public.archive_staff (person);

-- ----------------------------------------------------------------------------
-- 人物ビュー(キャストとスタッフの横断検索)
-- security_invoker = true が必須。付けないとビューがRLSを素通りし、
-- 公開キーから全件読めてしまう。
-- ----------------------------------------------------------------------------

create view public.archive_people with (security_invoker = true) as
select c.actor as person, c.actor_alias as alias, 'キャスト' as kind,
       c.role as detail, c.team as sub, r.perf_key, r.year, r.work, r.run_name
from public.archive_cast c join public.archive_runs r using (perf_key)
union all
select s.person, null, 'スタッフ',
       s.job, concat_ws(' / ', s.group_label, s.note), r.perf_key, r.year, r.work, r.run_name
from public.archive_staff s join public.archive_runs r using (perf_key)
where s.section <> '主催・協賛';

-- ----------------------------------------------------------------------------
-- 読み取り権限: ログインしたユーザーのみ(旧archive_castと同じ条件)。
-- 書き込みポリシーは作らない(データ投入はダッシュボードから)。
-- ビュー自体にもGRANTが必要(security_invokerは呼び出し元の権限で下位
-- テーブルのRLSを評価するだけで、ビュー自体の実行権限は別途必要)。
-- ----------------------------------------------------------------------------

grant select on public.archive_runs to authenticated;
grant select on public.archive_cast to authenticated;
grant select on public.archive_staff to authenticated;
grant select on public.archive_people to authenticated;

create policy "authenticated read archive_runs" on public.archive_runs
  for select to authenticated using (true);
create policy "authenticated read archive_cast" on public.archive_cast
  for select to authenticated using (true);
create policy "authenticated read archive_staff" on public.archive_staff
  for select to authenticated using (true);
